/*
having clause
1. It is used to filter the groups generated by group by clause
2. Executes after the group by  clause
3. MRF conndition's can be written having clause

Difference between Where and Having clause's
Where - Filter records
      - where clause executes row by row
      - written before group by clause
      - Group by clause not needed
      - MRF condition can not be used in where clause.
      - where clause is implemented on rows.

Having - Filter groups
       - having clause executes group by group
       - written after group by clause
       - Group by is must to use having clause
       - MRF condition can  be used in having clause.
       - having clause is implemented on columns.

Syntax:
        select gf/group by expression -->5 (group by group)
        from table_name    --> 1
        where <condition>  --> (row by row)
        group by expression   -->3
        having <condition>;    -->4 group by group

The HAVING condition cannot contain a scalar subquery expression.

*/
--Display number of employees working? in each department,
--if atleast 2 employees wroking in each department.

select deptno, count(ename)   -- 4
from emp   -- 1
group by deptno  -- 2
having count(ename) >= 2;  -- 3

--Display highest salary given to each department,
--if the employee's are working in department 20 or 30,
--also the highest salary of each department should be more than 1000

select deptno, max(sal)  -- 5
from emp   -- 1
where deptno in (20, 30) -- 2
group by deptno -- 3
having max(sal) > 1000; -- 4

--Display the salary that is repeated.
select sal, count(sal)  -- 4
from emp    -- 1
group by sal  -- 2
having count(sal) >= 2;  -- 3







