create table if not exists accounts (
	user_id SERIAL primary key,
	username varchar(50) unique not null,
	password varchar(10) not null,
	email varchar(255) unique not null,
	created_at timestamp not null,
	last_login timestamp
);


select * from accounts;


create table if not exists baskets(
	name varchar(255) not null
);

alter table public.baskets add column id serial primary key;

select pg_get_serial_sequence('baskets','id');


SELECT nextval(pg_get_serial_sequence('public.baskets', 'id'));



SELECT currval(pg_get_serial_sequence('public.baskets', 'id'));


create sequence sample_seq;

select nextval('sample_seq');

select currval('sample_seq');

select setval('sample_seq', 10);

drop sequence sample_seq;

create sequence custom_seq  
increment 5
minvalue 10
maxvalue 1000
start with 10
cycle;


select nextval('custom_seq');
select currval('custom_seq');

drop sequence if exists custom_seq;




create table if not exists order_details(

	order_id serial,
	item_id INT not null,
	item_text varchar not null,
	price DEC(10, 2) not null,
	primary key(order_id, item_id)
);


create sequence order_item_id
start 10
increment 10
minvalue 10
owned by order_details.item_id;

insert into 
	public.order_details(order_id, item_id, item_text, price)
values
	(100, nextval('order_item_id'), 'DVD Player', 100),
	(100, nextval('order_item_id'), 'Android TV', 550),
	(100, nextval('order_item_id'), 'Speaker', 250);

select *
from public.order_details od ;


select 
	relname sequence_name
from
	pg_class
where 
	relkind = 'S';


drop sequence if exists order_details_order_id_seq cascade;


select *
from public.order_details od ;



create table if not exists color(
	color_id INT GENERATED ALWAYS AS IDENTITY,
	color_name varchar not null
);

insert into public.color (color_name)
values('Red');

select *
from public.color c ;


insert into public.color (color_id , color_name)
overriding system value
values(10,'Red');




create table if not exists shape(
	shape_id int not null,
	shape_name varchar not null
);

alter table  public.shape 
alter column shape_id
add generated always as identity;


alter table public.shape 
alter column shape_id
set generated by default ;


alter table public.shape 
alter column shape_id
drop identity if exists;







CREATE table if not exists sales (
    region TEXT NOT NULL,
    country TEXT NOT NULL,
    item_type TEXT NOT NULL,
    sales_channel TEXT NOT NULL,
    order_priority CHAR(1) NOT NULL,
    order_date DATE NOT NULL,
    order_id BIGINT PRIMARY KEY,
    ship_date DATE NOT NULL,
    units_sold INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    unit_cost NUMERIC(10, 2) NOT NULL,
    total_revenue NUMERIC(15, 2) NOT NULL,
    total_cost NUMERIC(15, 2) NOT NULL,
    total_profit NUMERIC(15, 2) NOT NULL
);


select *
from public.sales s 
limit 15;



